RejestrFaktur/RejestrFaktur/Controllers/JednostkiMiaryController.cs
using RejestrFaktur.DAL;
using RejestrFaktur.Models;
using System.Net;
using System.Web.Mvc;
using RejestrFaktur.utils.AbstrKlasyInterfejsyGenerics;
using RejestrFaktur.utils.HelpersExtensions;
using RejestrFaktur.utils.impl.JednostkiMiary;
using RejestrFaktur.utils.pozostale;

namespace RejestrFaktur.Controllers
{
    public class JednostkiMiaryController : GenerycznyController<JednostkaMiary>
    {


        public JednostkiMiaryController()
        {
            dbcontext = new RejestrFakturContext();
            opakowanie = new Opakowanie<JednostkaMiary>(new JednostkiMiaryOperacje(), dbcontext);
            obslugaDelegaty = new ObslugaDelegaty<int, Stany>();

            obslugaDelegaty.delegaty += opakowanie.DoEdycji;
            obslugaDelegaty.delegaty += opakowanie.DoPodgladu;
            obslugaDelegaty.delegaty += opakowanie.DoUsuniencia;
            obslugaDelegaty.delegaty += opakowanie.Nowy;

        }

        [ActionName("EdycjaNowy"), AcceptVerbs("Post")]
        public override ActionResult Zapisz([Bind(Prefix = "Edytowany", Include = "Id,NazwaJednostki,SymbolJednostki")]JednostkaMiary t,
                             [Bind(Include = "StanObiektu")]Stany StanObiektu)
        {

            if (ModelState.IsValid)
            {
                if (opakowanie.ZapiszObiekt(t, StanObiektu))
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
            }
            else
            {
                opakowanie.ObiektDoWidoku.Edytowany = t;
                opakowanie.ObiektDoWidoku.StanObiektu = StanObiektu;
                return View(opakowanie.ObiektDoWidoku);
            }
        }

        [HttpPost]
        public override ActionResult Usun([Bind(Prefix = "Edytowany", Include = "Id,NazwaJednostki,SymbolJednostki")]JednostkaMiary t)
        {
            if (ModelState.IsValid)
            {
                if (opakowanie.UsunObiekt(t))
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
            }
            else
            {
                return RedirectToAction("Index");
            }
        }
    }
}

RejestrFaktur/RejestrFaktur/Controllers/PlatnosciTypController.cs
using System.Net;
using System.Web.Mvc;
using RejestrFaktur.DAL;
using RejestrFaktur.Models;
using RejestrFaktur.utils.AbstrKlasyInterfejsyGenerics;
using RejestrFaktur.utils.HelpersExtensions;
using RejestrFaktur.utils.impl.PlatnoscTyp;
using RejestrFaktur.utils.pozostale;

namespace RejestrFaktur.Controllers
{
    public class PlatnosciTypController :GenerycznyController<PlatnoscTyp>
    {

        public PlatnosciTypController()
        {
            dbcontext = new RejestrFakturContext();
            opakowanie = new Opakowanie<PlatnoscTyp>(new PlatnoscTypOperacje(), dbcontext);
            obslugaDelegaty = new ObslugaDelegaty<int, Stany>();

            obslugaDelegaty.delegaty += opakowanie.DoEdycji;
            obslugaDelegaty.delegaty += opakowanie.DoPodgladu;
            obslugaDelegaty.delegaty += opakowanie.DoUsuniencia;
            obslugaDelegaty.delegaty += opakowanie.Nowy;
        }


        [ActionName("EdycjaNowy"), AcceptVerbs("Post")]
        public override ActionResult Zapisz([Bind(Prefix = "Edytowany", Include = "Id,Nazwa,Opis")]PlatnoscTyp t, [Bind(Include = "StanObiektu")]Stany StanObiektu)
        {
            {

                if (ModelState.IsValid)
                {
                    if (opakowanie.ZapiszObiekt(t, StanObiektu))
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }
                }
                else
                {
                    opakowanie.ObiektDoWidoku.Edytowany = t;
                    opakowanie.ObiektDoWidoku.StanObiektu = StanObiektu;
                    return View(opakowanie.ObiektDoWidoku);
                }
            }
        }

        [HttpPost]
        public override ActionResult Usun([Bind(Prefix = "Edytowany", Include = "Id,Nazwa,Opis")]PlatnoscTyp t)
        {
            if (ModelState.IsValid)
            {
                if (opakowanie.UsunObiekt(t))
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
            }
            else
            {
                return RedirectToAction("Index");
            }
        }
    }
}

RejestrFaktur/RejestrFaktur/Controllers/StawkiPodatkuController.cs
using RejestrFaktur.DAL;
using RejestrFaktur.Models;
using System.Net;
using System.Web.Mvc;
using RejestrFaktur.utils.AbstrKlasyInterfejsyGenerics;
using RejestrFaktur.utils.HelpersExtensions;
using RejestrFaktur.utils.impl.StawkiPodatku;
using RejestrFaktur.utils.pozostale;

namespace RejestrFaktur.Controllers
{
    public class StawkiPodatkuController : GenerycznyController<StawkaPodatku>
    {

        public StawkiPodatkuController()
        {
            dbcontext = new RejestrFakturContext();
            opakowanie = new Opakowanie<StawkaPodatku>(new StawkiPodatkuOperacje(), dbcontext);
            obslugaDelegaty = new ObslugaDelegaty<int, Stany>();

            obslugaDelegaty.delegaty +=opakowanie.DoEdycji;
            obslugaDelegaty.delegaty +=opakowanie.DoPodgladu;
            obslugaDelegaty.delegaty += opakowanie.DoUsuniencia;
            obslugaDelegaty.delegaty += opakowanie.Nowy;
        }



        [ActionName("EdycjaNowy"), AcceptVerbs("Post")]
        public override ActionResult Zapisz([Bind(Prefix = "Edytowany", Include = "Id,NazwaStawki, WysokoscStawki")]StawkaPodatku sP,
                             [Bind(Include = "StanObiektu")]Stany StanObiektu)
        {

            if (ModelState.IsValid)
            {
                if (opakowanie.ZapiszObiekt(sP, StanObiektu))
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
            }
            else
            {
                opakowanie.ObiektDoWidoku.Edytowany = sP;
                opakowanie.ObiektDoWidoku.StanObiektu = StanObiektu;
                return View(opakowanie.ObiektDoWidoku);
            }

        }

        [HttpPost]
        public override ActionResult Usun([Bind(Prefix = "Edytowany", Include = "Id,NazwaStawki, WysokoscStawki")]StawkaPodatku sP)
        {
            if (ModelState.IsValid)
            {
                if (opakowanie.UsunObiekt(sP))
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
            }
            else
            {
                return RedirectToAction("Index");
            }
        }


    }
}

RejestrFaktur/RejestrFaktur/Controllers/WalutaController.cs
using RejestrFaktur.DAL;
using RejestrFaktur.Models;
using System.Web.Mvc;
using System.Net;
using RejestrFaktur.utils.AbstrKlasyInterfejsyGenerics;
using RejestrFaktur.utils.HelpersExtensions;
using RejestrFaktur.utils.impl.Waluta;
using RejestrFaktur.utils.pozostale;

namespace RejestrFaktur.Controllers
{
    public class WalutaController : GenerycznyController<Waluta>
    {

        public WalutaController()
        {
           dbcontext = new RejestrFakturContext();
           opakowanie = new Opakowanie<Waluta>(new WalutaOperacje(), dbcontext);
           obslugaDelegaty = new ObslugaDelegaty<int, Stany>();

            obslugaDelegaty.delegaty +=opakowanie.DoEdycji;
            obslugaDelegaty.delegaty +=opakowanie.DoPodgladu;
            obslugaDelegaty.delegaty +=opakowanie.DoUsuniencia;
            obslugaDelegaty.delegaty +=opakowanie.Nowy;
        }

        [ActionName("EdycjaNowy"), AcceptVerbs("Post")]
        public override ActionResult Zapisz([Bind(Prefix = "Edytowany", Include = "Id,Nazwa,Symbol,SciezkaDoIkony")]Waluta t, [Bind(Include = "StanObiektu")]Stany StanObiektu)
        {
            {

                if (ModelState.IsValid)
                {
                    if (opakowanie.ZapiszObiekt(t, StanObiektu))
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }
                }
                else
                {
                    opakowanie.ObiektDoWidoku.Edytowany = t;
                    opakowanie.ObiektDoWidoku.StanObiektu = StanObiektu;
                    return View(opakowanie.ObiektDoWidoku);
                }
            }
        }

        [HttpPost]
        public override ActionResult Usun([Bind(Prefix = "Edytowany", Include = "Id,Nazwa,Symbol,SciezkaDoIkony")]Waluta t)
        {
            if (ModelState.IsValid)
            {
                if (opakowanie.UsunObiekt(t))
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
            }
            else
            {
                return RedirectToAction("Index");
            }
        }
    }
}

RejestrFaktur/RejestrFaktur/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

RejestrFaktur/RejestrFaktur/Views/Shared/_templateBootstrap.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>

<div class="container">
    <div class="row">@Html.Partial("~/Views/Shared/menuGlowneBootstrap.cshtml")</div>
    <div class="row">@ViewBag.Title</div>
    @RenderBody()
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
</body>
</html>

RejestrFaktur/RejestrFaktur/Views/Shared/menuDodatkoweBootstrap.cshtml
<ul class="dropdown-menu">
    <li>@Html.ActionLink("Jednostki miary", "Index", "JednostkiMiary")</li>
    <li>@Html.ActionLink("Typy płatności", "Index", "PlatnosciTyp")</li>
    <li>@Html.ActionLink("Stawki podatku", "Index", "StawkiPodatku")</li>
    <li>@Html.ActionLink("Rodzaje walut", "Index", "Waluta")</li>
</ul>

RejestrFaktur/RejestrFaktur/Views/Shared/menuGlowneBootstrap.cshtml
<div class="nav navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#mojeMenu">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <h1 class="navbar-brand"><strong>Rejestr faktur </strong><small>ver. 0.00</small></h1>
        </div>
        <div class="collapse navbar-collapse" id="mojeMenu">
            <ul class="nav navbar-nav">
                <li >@Html.ActionLink("Strona główna", "Index", "Home")</li>
                <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Wartości słownikowe <b class="caret"></b></a>
                   @Html.Partial("~/Views/Shared/menuDodatkoweBootstrap.cshtml")          
                </li>
                <li>@Html.ActionLink("O nas", "About", "Home")</li>
                <li>@Html.ActionLink("Kontakt", "Contact", "Home")</li>
            </ul>
        </div>
    </div>
</div>