SphynxWeb/SphynxWeb/Models/BlogModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace SphynxWeb.Models
{
    public class BlogModel
    {
        public int PostID { get; set; }
        public string Post { get; set; }
        System.DateTime DataDodania { get; set; }
    }
}

SphynxWeb/SphynxWeb/Controllers/BlogModelsController.cs
using System.Linq;
using System.Net;
using System.Web.Mvc;
using PagedList;
using Repozytorium.Models;
using Repozytorium.Repo;
using Repozytorium.Repo.Abstract;

namespace SphynxWeb.Controllers
{
    public class BlogModelsController : Controller
    {
        private IBlogRepo repo;

        public BlogModelsController()
        {
            repo = new BlogRepo();
        }

        // GET: BlogModels
        //public ActionResult Index()
        //{
        //    return PartialView(repo.GetAllBlogs().ToList());
        //}
  



        public ActionResult Index(int? pNumber)
        {
            int pageNumber = pNumber ?? 1;
            int pageSize = 2;
            var aktualnosci = repo.GetAllBlogs();
         
            //return PartialView(repo.GetAllBlogs().ToList());
            return PartialView(aktualnosci.ToList().ToPagedList(pageNumber, pageSize));
        }
        [Authorize]
        // GET: BlogModels/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogModel blogModel = repo.GetBlogById(id);
            if (blogModel == null)
            {
                return HttpNotFound();
            }
            return View(blogModel);
        }

        // GET: BlogModels/Create
            [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: BlogModels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Name, Post,ShowOnStartPage")] BlogModel blogModel)
        {
            if (ModelState.IsValid)
            {
                repo.AddBlog(blogModel);
                return RedirectToAction("Index");
            }

            return View(blogModel);
        }

        // GET: BlogModels/Edit/5
            [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogModel blogModel = repo.GetBlogById(id);
            if (blogModel == null)
            {
                return HttpNotFound();
            }
            return View(blogModel);
        }

        // POST: BlogModels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PostId,Post,Category,ShowOnStartPage,AddDate")] BlogModel blogModel)
        {
            if (ModelState.IsValid)
            {
                repo.EditBlog(blogModel);
                return RedirectToAction("Index");
            }
            return View(blogModel);
        }

        // GET: BlogModels/Delete/5
            [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogModel blogModel = repo.DeleteBlog(id);
            if (blogModel == null)
            {
                return HttpNotFound();
            }
            return View(blogModel);
        }

        // POST: BlogModels/Delete/5
            [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            repo.DeleteBlog(id);
            return RedirectToAction("Index");
        }

        public ActionResult GetDetails(int? id)
        {
            return Content(repo.GetBlogById(id).Post);
        } 
    }
}

SphynxWeb/SphynxWeb/Views/BlogModels/Create.cshtml
@model Repozytorium.Models.BlogModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


    <h4>BlogModel</h4>
    <hr />
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-horizontal">
            <div class="row">1</div>
            <div class="row">2</div>
            <div class="row">3</div>
            <div class="row">4</div>
            <div class="row">5</div>
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new {@class = "control-label col-md-2"})
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new {htmlAttributes = new {@class = "form-control"}})
                    @Html.ValidationMessageFor(model => model.Name, "", new {@class = "text-danger"})
                </div>
            </div>





            <div class="form-group">
                @Html.LabelFor(model => model.Post, htmlAttributes: new {@class = "control-label col-md-2"})
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Post, new {htmlAttributes = new {@class = "form-control"}})
                    @Html.ValidationMessageFor(model => model.Post, "", new {@class = "text-danger"})
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ShowOnStartPage, htmlAttributes: new {@class = "control-label col-md-2"})
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.ShowOnStartPage)
                        @Html.ValidationMessageFor(model => model.ShowOnStartPage, "", new {@class = "text-danger"})
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default"/>
                </div>
            </div>
        </div>
    }

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SphynxWeb/SphynxWeb/Views/BlogModels/Delete.cshtml
@model Repozytorium.Models.BlogModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BlogModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Post)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Post)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShowOnStartPage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShowOnStartPage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AddDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AddDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SphynxWeb/SphynxWeb/Views/BlogModels/Details.cshtml
@model Repozytorium.Models.BlogModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>BlogModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Post)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Post)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShowOnStartPage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShowOnStartPage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AddDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AddDate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.PostId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SphynxWeb/SphynxWeb/Views/BlogModels/Edit.cshtml
@model Repozytorium.Models.BlogModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>BlogModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.PostId)

        <div class="form-group">
            @Html.LabelFor(model => model.Post, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Post, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Post, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Category, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShowOnStartPage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.ShowOnStartPage)
                    @Html.ValidationMessageFor(model => model.ShowOnStartPage, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AddDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AddDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AddDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SphynxWeb/SphynxWeb/Views/BlogModels/Index.cshtml
@*@model IEnumerable<Repozytorium.Models.BlogModel>*@
@using PagedList.Mvc

@model PagedList.IPagedList<Repozytorium.Models.BlogModel> 
<link href="/Content/css/1-col-portfolio.css" rel="stylesheet">
@{
    ViewBag.Title = "Index";
    Styles.Render("~/Content/css");


}
<div id="pagination">
   
        @foreach (var item in Model)
    {
            <div class="row">

                <div class="col-md-12">
                    <h1>
                        @Html.DisplayFor(modelItem => item.AddDate) -
                        @Html.DisplayFor(modelItem => item.Name)
                    </h1>

                    <div id="cos">
                        <h4 id=@item.PostId.ToString()>
                            @* @Html.DisplayFor(modelItem => item.Post)*@
                            @item.Post.Split('\n')[0]...
                            <br>
                            @Ajax.ActionLink("Czytaj wiecej", "GetDetails", new RouteValueDictionary(new {id = item.PostId}), new AjaxOptions()
                        {
                            InsertionMode = InsertionMode.Replace,
                            UpdateTargetId = item.PostId.ToString()
                        })
                        </h4>


                    </div>

                    @*<a class="btn btn-primary" href="#">View Project <span class="glyphicon glyphicon-chevron-right"></span></a>*@
                </div>
            </div>
    }
        <ul class="pagination">
            <li>
                @*@Html.PagedListPager(Model, page => Url.Action("Index", new RouteValueDictionary(new { pNumber = page })))*@

                @Html.PagedListPager(Model, page => Url.Action("Index", "BlogModels", new RouteValueDictionary(new {pNumber = page})), PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions() {InsertionMode = InsertionMode.Replace, UpdateTargetId = "pagination"}))
            </li>

        </ul>
    </div>










    @*<div class="service text-center">
            <div class="row">
                <div class="col-xs-2 col-sm-2 col-md-2">

                </div>
                <div class="col-xs-8 col-sm-8 col-md-8">
                    <h1>Aktualności w budowie </h1>
                </div>
                <div class="col-xs-2 col-sm-2 col-md-2">

                </div>
            </div>

            @foreach (var item in Model)
            {
                <div class="container">
                    <div class="row">

                        <div class="col-xs-4 col-sm-4 col-md-4"> @Html.DisplayFor(modelItem => item.AddDate)</div>

                        <div class="col-xs-8 col-sm-8 col-md-8"> @Html.DisplayFor(modelItem => item.Name)</div>
                        <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-12">@Html.DisplayFor(modelItem => item.Post)</div>
                        </div>
                    </div>
                </div>

            }
        </div>*@


    @*<table class="table">
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.AddDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Post)
                    </td>

                    @*   <td>
                            @Html.ActionLink("Edit", "Edit", new { id=item.PostId }) |
                            @Html.ActionLink("Details", "Details", new { id=item.PostId }) |
                            @Html.ActionLink("Delete", "Delete", new { id=item.PostId })
                        </td>
                </tr>
            }

        </table>*@